# Generated by Django 5.1.15 on 2026-05-27 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industries', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='industries',
            field=models.ManyToManyField(blank=True, help_text='Market segments this product serves; powers industry landing pages.', related_name='products', to='industries.industry'),
        ),
    ]
