# Generated by Django 5.1.15 on 2026-05-28 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('publication', models.CharField(help_text='e.g. "Dawn Business"', max_length=200)),
                ('url', models.URLField()),
                ('excerpt', models.CharField(blank=True, max_length=400)),
                ('published_on', models.DateField(db_index=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Media coverage',
                'verbose_name_plural': 'Media coverage',
                'ordering': ['-published_on'],
                'indexes': [models.Index(fields=['is_active', '-published_on'], name='media_cente_is_acti_dbaaab_idx'), models.Index(fields=['is_featured', '-published_on'], name='media_cente_is_feat_68cb43_idx')],
            },
        ),
        migrations.CreateModel(
            name='PressRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('slug', models.SlugField(max_length=240, unique=True)),
                ('summary', models.CharField(max_length=300)),
                ('body', models.TextField()),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='media/press/%Y/')),
                ('pdf', models.FileField(blank=True, help_text='Optional downloadable PDF version of the release.', null=True, upload_to='media/press/pdf/%Y/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=16)),
                ('issued_on', models.DateField(blank=True, db_index=True, help_text='Date of release. Displayed publicly. Distinct from created_at.', null=True)),
                ('seo_title', models.CharField(blank=True, max_length=70)),
                ('seo_description', models.CharField(blank=True, max_length=170)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-issued_on', '-created_at'],
                'indexes': [models.Index(fields=['status', '-issued_on'], name='media_cente_status_ba63e2_idx')],
            },
        ),
    ]
