# Generated by Django 5.1.15 on 2026-05-27 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('category', models.CharField(choices=[('agronomy', 'Agronomy support'), ('manufacturing', 'Contract manufacturing'), ('formulation', 'Formulation development'), ('logistics', 'Logistics & supply'), ('other', 'Other')], db_index=True, max_length=24)),
                ('summary', models.CharField(max_length=300)),
                ('body', models.TextField(blank=True, help_text='Long-form description.')),
                ('deliverables', models.JSONField(blank=True, default=list, help_text='List of deliverables, e.g. ["Field visit", "Soil sampling", "Written report"].')),
                ('typical_timeline', models.CharField(blank=True, help_text='e.g. "4–6 weeks"', max_length=120)),
                ('pricing_model', models.CharField(blank=True, help_text='e.g. "Fixed scope" or "Time & materials".', max_length=140)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('position', models.PositiveIntegerField(db_index=True, default=0)),
                ('seo_title', models.CharField(blank=True, max_length=70)),
                ('seo_description', models.CharField(blank=True, max_length=170)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['position', 'name'],
                'indexes': [models.Index(fields=['is_active', 'position'], name='services_se_is_acti_30fb53_idx'), models.Index(fields=['category', 'is_active'], name='services_se_categor_4c373a_idx')],
            },
        ),
        migrations.CreateModel(
            name='ServiceEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('company', models.CharField(blank=True, max_length=140)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('offering', models.ForeignKey(blank=True, help_text='Service the customer is enquiring about. Optional — may be a general services enquiry.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enquiries', to='services.serviceoffering')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['offering', '-created_at'], name='services_se_offerin_3ffd86_idx')],
            },
        ),
    ]
