# Generated by Django 5.1.15 on 2026-05-28 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('company', models.CharField(blank=True, max_length=140)),
                ('enquiry_type', models.CharField(choices=[('sales', 'Sales / Quote'), ('technical', 'Technical Support'), ('partnership', 'Partnership'), ('careers', 'Careers'), ('media', 'Media / Press'), ('other', 'Other')], db_index=True, max_length=24)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('responded', 'Responded'), ('closed', 'Closed'), ('spam', 'Spam / Discarded')], db_index=True, default='new', max_length=24)),
                ('internal_notes', models.TextField(blank=True, help_text='Staff notes. Never shown to the customer.')),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('submitter_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='contact_con_status_4b75ca_idx'), models.Index(fields=['enquiry_type', '-created_at'], name='contact_con_enquiry_750e3b_idx')],
            },
        ),
    ]
