# Generated by Django 5.1.15 on 2026-05-27 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('summary', models.CharField(help_text='One-line summary used in cards and meta description fallback.', max_length=300)),
                ('body', models.TextField(blank=True, help_text='Long-form description rendered on the industry detail page.')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='industries/%Y/')),
                ('icon', models.CharField(blank=True, help_text="Short label key (e.g. 'wheat') for icon selection in templates.", max_length=40)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('position', models.PositiveIntegerField(db_index=True, default=0)),
                ('seo_title', models.CharField(blank=True, max_length=70)),
                ('seo_description', models.CharField(blank=True, max_length=170)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'industries',
                'ordering': ['position', 'name'],
                'indexes': [models.Index(fields=['is_active', 'position'], name='industries__is_acti_791c70_idx')],
            },
        ),
    ]
