# Generated by Django 5.1.15 on 2026-05-30 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="gateway",
            field=models.CharField(
                choices=[
                    ("jazzcash", "JazzCash"),
                    ("easypaisa", "EasyPaisa"),
                    ("hbl", "HBL"),
                    ("meezan", "MeezanPay"),
                    ("bank_transfer", "Bank Transfer"),
                    ("cod", "Cash on Delivery"),
                ],
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="paymentevent",
            name="gateway",
            field=models.CharField(
                choices=[
                    ("jazzcash", "JazzCash"),
                    ("easypaisa", "EasyPaisa"),
                    ("hbl", "HBL"),
                    ("meezan", "MeezanPay"),
                    ("bank_transfer", "Bank Transfer"),
                    ("cod", "Cash on Delivery"),
                ],
                max_length=24,
            ),
        ),
    ]
