# Generated by Django 5.1.15 on 2026-05-28 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(db_index=True, help_text='Absolute URL path, e.g. "/products/urea/". Trailing slash required.', max_length=400, unique=True)),
                ('title', models.CharField(blank=True, help_text='Recommended 50–60 chars including brand.', max_length=70)),
                ('description', models.CharField(blank=True, help_text='Recommended 140–160 chars.', max_length=170)),
                ('canonical_url', models.URLField(blank=True, help_text='Override the canonical URL. Leave blank to use request URL.')),
                ('og_title', models.CharField(blank=True, max_length=120)),
                ('og_description', models.CharField(blank=True, max_length=200)),
                ('og_image', models.ImageField(blank=True, help_text='Recommended 1200×630.', null=True, upload_to='seo/og/')),
                ('noindex', models.BooleanField(default=False, help_text='Adds <meta name=robots content=noindex>.')),
                ('nofollow', models.BooleanField(default=False)),
                ('extra_json_ld', models.JSONField(blank=True, default=dict, help_text='Optional JSON-LD object merged into the page (overrides per-page default).')),
                ('notes', models.TextField(blank=True, help_text='Internal notes — not rendered.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page metadata',
                'verbose_name_plural': 'Page metadata',
                'ordering': ['path'],
            },
        ),
        migrations.CreateModel(
            name='RobotsRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directive', models.CharField(choices=[('user_agent', 'User-agent'), ('disallow', 'Disallow'), ('allow', 'Allow'), ('crawl_delay', 'Crawl-delay'), ('comment', 'Comment (# prefix)')], max_length=20)),
                ('value', models.CharField(max_length=400)),
                ('position', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Redirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_path', models.CharField(db_index=True, help_text='e.g. "/old-product/" — match is exact.', max_length=400, unique=True)),
                ('target_url', models.CharField(help_text='Either a relative path or an absolute URL.', max_length=600)),
                ('status_code', models.PositiveSmallIntegerField(choices=[(301, '301 Permanent'), (302, '302 Temporary')], default=301)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('hits', models.PositiveIntegerField(default=0, help_text='Increments each time this redirect fires.')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['source_path'],
                'indexes': [models.Index(fields=['is_active', 'source_path'], name='seo_redirec_is_acti_edd307_idx')],
            },
        ),
    ]
