# Generated by Django 5.1.15 on 2026-05-27 19:58

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('position', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ShippingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='PK', max_length=2)),
                ('min_weight_kg', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=8)),
                ('max_weight_kg', models.DecimalField(decimal_places=3, max_digits=8)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('currency', models.CharField(default='PKR', max_length=3)),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='shipping.shippingmethod')),
            ],
            options={
                'ordering': ['country', 'min_weight_kg'],
                'indexes': [models.Index(fields=['method', 'country', 'min_weight_kg'], name='shipping_sh_method__450d71_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('max_weight_kg__gt', models.F('min_weight_kg'))), name='shipping_rate_max_gt_min_weight')],
            },
        ),
    ]
