# Generated by Django 5.1.15 on 2026-05-28 04:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('logout', 'Logout'), ('login_failed', 'Login failed'), ('order_transition', 'Order status transition'), ('payment_received', 'Payment received'), ('payment_failed', 'Payment failed'), ('refund', 'Refund issued'), ('publish', 'Publish'), ('unpublish', 'Unpublish'), ('permission_change', 'Permission change'), ('export', 'Data export'), ('other', 'Other')], db_index=True, max_length=32)),
                ('actor_label', models.CharField(blank=True, help_text='Snapshot of actor identity (email/username) at log time — survives user deletion.', max_length=200)),
                ('target_type', models.CharField(blank=True, db_index=True, help_text='e.g. "orders.Order" or "products.Product".', max_length=120)),
                ('target_id', models.CharField(blank=True, db_index=True, help_text='Primary key (or UUID) of the target row, as a string.', max_length=64)),
                ('target_label', models.CharField(blank=True, help_text="Snapshot of the target's str() for human-readable logs.", max_length=200)),
                ('description', models.CharField(blank=True, max_length=400)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, help_text='Who performed the action. NULL for system / anonymous.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', '-created_at'], name='audit_audit_action_5a2cbc_idx'), models.Index(fields=['target_type', 'target_id', '-created_at'], name='audit_audit_target__14244e_idx'), models.Index(fields=['actor', '-created_at'], name='audit_audit_actor_i_55fb6e_idx')],
            },
        ),
    ]
