# Generated by Django 5.1.15 on 2026-05-28 04:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRollup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(db_index=True, max_length=400)),
                ('date', models.DateField(db_index=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('unique_sessions', models.PositiveIntegerField(default=0)),
                ('events', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', 'path'],
                'indexes': [models.Index(fields=['-date', 'path'], name='analytics_d_date_ca928c_idx')],
                'constraints': [models.UniqueConstraint(fields=('path', 'date'), name='rollup_unique_path_date')],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text="Short event name, e.g. 'add_to_cart', 'checkout_start'.", max_length=80)),
                ('path', models.CharField(blank=True, db_index=True, max_length=400)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['name', '-created_at'], name='analytics_e_name_19adf9_idx'), models.Index(fields=['session_key', '-created_at'], name='analytics_e_session_7d58a8_idx')],
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(db_index=True, max_length=400)),
                ('referrer', models.CharField(blank=True, max_length=600)),
                ('session_key', models.CharField(blank=True, db_index=True, help_text='Django session key for uniqueness checks.', max_length=40)),
                ('ip_prefix', models.CharField(blank=True, db_index=True, max_length=45)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['path', '-created_at'], name='analytics_p_path_33d66e_idx')],
            },
        ),
    ]
